WDM.Web/Controllers/SinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LRBDYS.OAuthPlugin.Weibo;
using LRBDYS.OAuthPlugin.Weibo.AccessToken;
using LRBDYS.OAuthPlugin.Weibo.Api;
using LRBDYS.OAuthPlugin.Weibo.Common;
using LRBDYS.OAuthPlugin.Weibo.Interface;
using WDM.Web.Filters;

namespace WDM.Web.Controllers
{
    /// <summary>
    /// 暂未测试
    /// </summary>
    public class SinaController : Controller
    {
        private IAuthorizationCodeBase _authCode = AccessTokenFactory.Create(CreateAT.Sina);
        private SinaError _err = null;
        private IApi api = AccessTokenFactory.Create(CreateApi.Sina);

        public ActionResult Index(string code)
        {
            if (Session["accessToken"] != null)
            {
                return View(new object());
            }

            if (!string.IsNullOrEmpty(code))
            {
                var redirectUrl = AccessTokenToolkit.GenerateHostPath(Request.Url) + Url.Action("Index");

                var accessToken = _authCode.GetResult(_authCode.GenerateAccessTokenUrl(redirectUrl, code));

                if (api.IsError(accessToken, out _err))
                {
                    Session["err"] = _err;
                    return RedirectToAction("Error");
                }

                Session.Add("accessToken", accessToken);

                return View(new object());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [AccessTokenRequired]
        public ActionResult ShowUserInfo()
        {
            var accessTokenObj = Session["accessToken"] as dynamic;
            var uid = accessTokenObj.uid;
            var accessToken = accessTokenObj.access_token;

            var model = api.CallGet("users/show.json?uid=" + uid, accessToken);

            if (api.IsError(model, out _err))
            {
                Session["err"] = _err;
                return RedirectToAction("Error");
            }

            return View(model);
        }

        [AccessTokenRequired]
        public ActionResult SendMsg()
        {
            var accessTokenObj = Session["accessToken"] as dynamic;
            var uid = accessTokenObj.uid;
            var accessToken = accessTokenObj.access_token;

            //msg:要发表的微博信息
            var msg = "新浪微博api接口测试   测试人：∮〆﹏落日般的忧伤づミ   时间：" + DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss");
            var formData = new Dictionary<string, string>();
            formData.Add("status", Server.UrlEncode(msg));

            var result = api.CallPost("statuses/update.json", accessToken, formData, true);

            if (api.IsError(result, out _err))
            {
                Session["err"] = _err;
                return RedirectToAction("Error");
            }

            return View();
        }

        [AccessTokenRequired]
        public ActionResult SendMsgWithImg()
        {
            return View();
        }

        [HttpPost]
        [AccessTokenRequired]
        public ActionResult SendMsgWithImg(FormCollection form)
        {
            var accessTokenObj = Session["accessToken"] as dynamic;
            var uid = accessTokenObj.uid;
            string accessToken = accessTokenObj.access_token;

            Dictionary<string, string> formData = new Dictionary<string, string>();
            formData.Add("status", Url.Encode(Request.Form["status"]));

            Dictionary<string, BinaryData> binaryData = new Dictionary<string, BinaryData>();
            BinaryData bd = new BinaryData();
            bd.FileName = System.IO.Path.GetFileName(Request.Files["pic"].FileName);
            bd.ContentType = Request.Files["pic"].ContentType;

            var stream = Request.Files["pic"].InputStream;
            var readerStream = new System.IO.BinaryReader(stream);

            bd.Binary = readerStream.ReadBytes((int)stream.Length);

            binaryData.Add("pic", bd);

            var result = string.Empty;

            try
            {
                result = api.CallPost("statuses/upload.json", accessToken, formData, binaryData);
            }
            catch (System.Net.WebException wEx)
            {
                var srcStream = wEx.Response.GetResponseStream();

                var rStream = new System.IO.StreamReader(srcStream, System.Text.Encoding.UTF8);
                result = rStream.ReadToEnd();

            }




            return View((object)result);
        }

        public ActionResult Error()
        {
            var err = Session["err"] as SinaError;
            return View(err);
        }
    }
}

WDM.Web/Views/Sina/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model object

<h2>操作</h2>
<p>@Html.ActionLink("返回", "Index", "Home")</p>
@if (Model != null)
{
    @Html.ActionLink("显示用户信息", "ShowUserInfo") <text> | </text>
    @Html.ActionLink("发送测试微博", "SendMsg") <text> | </text>
    @Html.ActionLink("发送带图片的微博", "SendMsgWithImg")
}

WDM.Web/Views/Sina/SendMsg.cshtml
@{
    ViewBag.Title = "Send";
}

<h2>发送成功</h2>

WDM.Web/Views/Sina/SendMsgWithImg.cshtml
@{
    ViewBag.Title = "SendMsgWithImg";
}

<h2>PublishMsgWithImg</h2>

@using (Html.BeginForm("PublishMsgWithImg", "Sina", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <span>微博：</span>@Html.TextBox("status", "发表微博测试", new { style = "width: 900px;" })<br />
    <span>图片：</span><input type="file" id="pic" name="pic" /><br />
    <input type="submit" value="转发" />
    
}

@if (Model != null)
{
    <br /><text>发送成功</text><br />
    @Model.ToString();
}

WDM.Web/Views/Sina/ShowUserInfo.cshtml
@{
    ViewBag.Title = "ShowUserInfo";
}

<h2>用户：@Model.screen_name</h2>
<p>
用户UID: @Model.id<br />
用户昵称: @Model.screen_name<br />
友好显示名称: @Model.name<br />
用户所在地区ID: @Model.province<br />
用户所在城市ID: @Model.city<br />
用户所在地: @Model.location<br />
用户描述: @Model.description<br />
用户博客地址: @Model.url<br />
用户头像地址: @Model.profile_image_url @MvcHtmlString.Create(string.Format("<img src='{0}' />", Model.profile_image_url))<br />
用户的个性化域名: @Model.domain<br />
性别(m：男、f：女、n：未知): @Model.gender<br />
粉丝数: @Model.followers_count<br />
关注数: @Model.friends_count<br />
微博数: @Model.statuses_count<br />
收藏数: @Model.favourites_count<br />
创建时间: @Model.created_at<br />
当前登录用户是否已关注该用户: @Model.following<br />
是否允许所有人给我发私信: @Model.allow_all_act_msg<br />
是否允许带有地理信息: @Model.geo_enabled<br />
是否是微博认证用户，即带V用户: @Model.verified<br />
是否允许所有人对我的微博进行评论: @Model.allow_all_comment<br />
用户大头像地址: @Model.avatar_large @MvcHtmlString.Create(string.Format("<img src='{0}' />", @Model.avatar_large))<br />
认证原因: @Model.verified_reason<br />
该用户是否关注当前登录用户: @Model.follow_me<br />
用户的在线状态，0：不在线、1：在线: @Model.online_status<br />
用户的互粉数: @Model.bi_followers_count<br />
</p>